[workspace]
resolver = "2"
members = [
    "dynamic_script_engine",
    "node_macros",
    "general_wheel_cpp",
    "zihuan_core",
    "zihuan_service",
    "zihuan_workspace_service",
    "zihuan_ims_service",
    "zihuan_cli",
]
default-members = ["zihuan_service", "zihuan_cli"]

[workspace.dependencies]
tokenizers = "0.22.2"

[patch.crates-io]
candle-transformers = { path = "third_party/candle-transformers" }
