from typing import Any, Callable, TypeAlias
JsonValue: TypeAlias = str | int | float | bool | None | list["JsonValue"] | dict[str, "JsonValue"]
class ResourceHandle:
    """Purpose: opaque Rust-owned resource that can be passed to SDK calls and node outputs."""
    handle: str
    data_type: str
    def __init__(self, handle: str, data_type: str) -> None: ...
    def to_json(self) -> dict[str, str]: ...
class RedisRef(ResourceHandle): ...
class RdbRef(ResourceHandle): ...
class S3Ref(ResourceHandle): ...
class WeaviateRef(ResourceHandle): ...
class WebSearchEngineRef(ResourceHandle): ...
class SessionStateRef(ResourceHandle): ...
class LLMMessageSessionCacheRef(ResourceHandle): ...
class LLModel(ResourceHandle): ...
class EmbeddingModel(ResourceHandle): ...
class BotAdapterRef(ResourceHandle): ...
class NodeExecutionContext:
    """Purpose: values and capabilities available during one Python node execution."""
    node_id: str
    node_name: str
    inputs: dict[str, Any]
    inline_values: dict[str, Any]
    zihuan: ZihuanSdk
class Port:
    """Purpose: declare an input or output port in a Python node decorator."""
    def __init__(self, name: str, data_type: Any, required: bool = True, hidden: bool = False, description: str | None = None) -> None: ...
class ZihuanSdk:
    """Purpose: root object exposing all Rust-hosted dynamic-script capabilities."""
    variables: Any; task: Any; session: Any; message_cache: Any; models: Any; embeddings: Any; search: Any; storage: Any; agent: Any; bot: Any; resources: Any
def node(*, type_id: str, display_name: str, category: str, description: str = ..., input_ports: list[Port] | None = ..., output_ports: list[Port] | None = ..., dynamic_input_ports: bool = ..., dynamic_output_ports: bool = ..., config_fields: list[dict[str, Any]] | None = ..., resolve_ports: Callable[[dict[str, Any]], dict[str, list[Port]]] | None = ...) -> Callable[[Callable[[NodeExecutionContext], dict[str, Any]]], Callable[[NodeExecutionContext], dict[str, Any]]]:
    """Purpose: register a function as a discoverable Python DAG node."""
    ...
def hydrate_resources(value: Any) -> Any: ...
