//! Integration tests for the message snapshot restore helpers in
//! `zihuan_graph_engine::message_restore`.
//!
//! These tests exercise the two complementary rebuild paths used when a
//! persisted message snapshot is restored:
//!
//! 1. [`rebuild_message_list`] — rebuilds messages from a free-text `content`
//!    string plus a serialized `Vec<MessageMediaRecord>` (`media_json`). This is
//!    the fallback branch used when the raw message JSON is unavailable.
//! 2. [`rebuild_message_list_from_raw_json`] — deserializes a full
//!    `Vec<Message>` from the stored `raw_message_json`. This is the preferred
//!    branch and relies on `ImageMessage`'s custom `Deserialize` implementation
//!    to restore nested `PersistedMedia` data.

use zihuan_core::ims_bot_adapter::models::message::{
    ImageMessage, Message, MessageMediaRecord, PersistedMedia, PersistedMediaSource,
};
use zihuan_core::graph::message_restore::{
    rebuild_message_list, rebuild_message_list_from_raw_json,
};

/// Purpose:
///     Verify that `rebuild_message_list` correctly rebuilds an `Image` message
///     from a serialized `Vec<MessageMediaRecord>` (`media_json`) when the
///     free-text `content` is empty.
///
///     This guards the fallback restore branch used when `raw_message_json` is
///     missing (e.g. legacy snapshots), ensuring every field of the flat media
///     record is faithfully mapped back onto a `PersistedMedia` embedded in an
///     `ImageMessage`.
///
/// Test Data:
///     - `content` is an empty string, so no plain-text segment is produced.
///     - `media_json` is a serialized list with a single `MessageMediaRecord`:
///         * segment_index: 0
///         * type: "image"
///         * media_id: "media-1"
///         * source: PersistedMediaSource::QqChat
///         * original_source: "https://multimedia.nt.qq.com.cn/download?fileid=1"
///         * rustfs_path: "qq-images/2026/05/16/1.jpg"
///         * name: Some("download")
///         * description: Some("图片描述")
///         * mime_type: Some("image/jpeg")
///
/// Expected outcome:
///     The rebuilt list contains exactly one `Message::Image` whose
///     `PersistedMedia` preserves `media_id`, `rustfs_path`, and `mime_type`.
#[test]
fn rebuild_message_list_from_media_json_restores_persisted_media_image() {
    let media_json = serde_json::to_string(&vec![MessageMediaRecord {
        segment_index: 0,
        r#type: "image".to_string(),
        media_id: "media-1".to_string(),
        source: PersistedMediaSource::QqChat,
        original_source: "https://multimedia.nt.qq.com.cn/download?fileid=1".to_string(),
        rustfs_path: "qq-images/2026/05/16/1.jpg".to_string(),
        name: Some("download".to_string()),
        description: Some("图片描述".to_string()),
        mime_type: Some("image/jpeg".to_string()),
    }])
    .expect("serialize media json");

    let messages = rebuild_message_list("", Some(&media_json));
    match &messages[0] {
        Message::Image(image) => {
            assert_eq!(image.media.media_id, "media-1");
            assert_eq!(image.media.rustfs_path, "qq-images/2026/05/16/1.jpg");
            assert_eq!(image.media.mime_type.as_deref(), Some("image/jpeg"));
        }
        other => panic!("expected image message, got {other:?}"),
    }
}

/// Purpose:
///     Verify that `rebuild_message_list_from_raw_json` correctly deserializes
///     a full `Vec<Message>` from `raw_message_json`, including the nested
///     `PersistedMedia` stored inside an `ImageMessage`.
///
///     This guards the preferred restore branch used by the Redis / MySQL
///     snapshot flow. In particular it ensures `ImageMessage`'s custom
///     `Deserialize` implementation picks the `{"media": {...}}` branch (rather
///     than the NapCat `{file, url}` fallback) and that key media locators
///     survive the serialize -> deserialize round-trip.
///
/// Test Data:
///     - A `Vec<Message>` with a single `Message::Image` created from
///       `PersistedMedia::new`:
///         * source: PersistedMediaSource::Upload
///         * original_source: "upload://manual/demo"
///         * rustfs_path: "uploads/demo.png"
///         * name: Some("demo.png")
///         * description: None
///         * mime_type: Some("image/png")
///       (`media_id` is auto-generated by `PersistedMedia::new` and is not
///       asserted here because its format depends on wall-clock time.)
///     - The messages are serialized with `serde_json` to produce
///       `raw_message_json`, mimicking the payload stored in the snapshot.
///
/// Expected outcome:
///     The restored list has length 1 and its image's `rustfs_path` is
///     "uploads/demo.png".
#[test]
fn rebuild_message_list_from_raw_json_restores_nested_media() {
    let messages = vec![Message::Image(ImageMessage::new(PersistedMedia::new(
        PersistedMediaSource::Upload,
        "upload://manual/demo",
        "uploads/demo.png",
        Some("demo.png".to_string()),
        None,
        Some("image/png".to_string()),
    )))];
    let raw_json = serde_json::to_string(&messages).expect("serialize messages");
    let restored = rebuild_message_list_from_raw_json(&raw_json).expect("restore raw json");
    assert_eq!(restored.len(), 1);
    match &restored[0] {
        Message::Image(image) => {
            assert_eq!(image.media.rustfs_path, "uploads/demo.png");
        }
        other => panic!("expected image message, got {other:?}"),
    }
}
