name: Check

permissions:
  contents: read

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Restore Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Check workspace
        run: cargo check --workspace

      - name: Lint workspace
        run: cargo clippy --workspace

      - name: Check formatting
        run: cargo fmt --check --all
